#!/usr/bin/python

DOCUMENTATION='''
---
'''

EXAMPLES='''
'''

# import sys
try:
    import json
except ImportError:
    import simplejson as json
# import os
# import shlex

import rpm


def main():
    module=AnsibleModule(
            argument_spec = dict(
                    names=dict(type='list',required=True),
                    state=dict(choices=["absent", "present"], default='present'),
                )
        )

    state = module.params['state']
    packages=module.params['names']
    
    ts = rpm.TransactionSet()

    # rpm.addMacro("_dbpath", path_to_rpm_database)
    res={}
    
    for p in packages:
    
        mi = ts.dbMatch('name', p)
        
        if not mi:
            res[p]={'state':'absent'}
            
        while mi:
            try:
                h = mi.next()
            except StopIteration:
                if not res.has_key(p):
                    res[p]={'state':'absent'}
                break
            res[p]={'version':h['version'],'release':h['release'],'state':'present'}
            # print "%s-%s-%s" % (h['name'], h['version'], h['release'])
            
    module.exit_json(changed=True,ansible_facts=res)
    # print json.dumps({"changed":"True","ansible_facts":res})
    
    
# include magic from lib/ansible/module_common.py
#<<INCLUDE_ANSIBLE_MODULE_COMMON>>
main()
