---
# The common tasks

- name: copy yum repo files 
  copy: src={{ item }} dest=/etc/yum.repos.d/
  with_items:
   - epel.repo 
   - epel-openstack-grizzly.repo
  tags: install       
   

- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg
  tags: install       

- name: Install required packages
  yum: name={{ item }} state=installed
  with_items:
   - ntp
   - sudo
   - scsi-target-utils
   - dbus
   - libselinux-python
  notify: restart services 
  tags: install     
  
- name: Check for required OS packages
  rpm: names={{ item }} state=present
  with_items:
   - ntp
   - sudo
   - scsi-target-utils
   - dbus
   - libselinux-python
  notify: restart services 
  tags: check     

- name: Create the hosts entry.
  template: src=hosts.j2 dest=/etc/hosts
  tags: setup       

- name: Disable selinux dynamically
  shell: creates=/etc/sysconfig/selinux.disabled setenforce 0 ; touch /etc/sysconfig/selinux.disabled
  tags: setup       

- name: Disable SELinux in conf file
  copy: src=selinux dest=/etc/sysconfig/selinux
  tags: setup       

- name: Disable iptables
  service: name=iptables state=stopped enabled=no
  tags: setup       



