---
# The common tasks

- name: copy yum repo files 
  copy: src={{ item }} dest=/etc/yum.repos.d/
  with_items:
   - epel.repo 
   - epel-openstack-grizzly.repo
  tags: install       
   

- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg
  tags: install       

- name: Install required packages
  yum: name={{ item }} state=installed
  with_items:
   - ntp
   - sudo
   - scsi-target-utils
   - dbus
   - libselinux-python
   - openssl-devel
  notify: restart services 
  tags: install     
  
- name: Check for required packages
  rpm: name={{ item }} state=present
  with_items:
   - ntp
   - sudo
   - scsi-target-utils
   - dbus
   - libselinux-python
   - openssl-devel
  notify: restart services 
  tags: check     

- name: Remove previous openvwitch if installed
  yum: name=openvswitch-1.9.0 state=absent
  tags: install       

- name: Check if custom Openvswitch is installed
  shell: rpm -qa | grep kmod-openvswitch-1.10 | cut -d- -f3
  register: vswitch_version
  tags: install       

- name: Install Development tools
  shell: yum -y groupinstall "Development Tools"
  when: vswitch_version.stdout != '1.10.0'
  tags: install       

- name: Create the directories for compiling the openvswitch source
  file: path=/root/rpmbuild/SOURCES state=directory
  tags: install       

- name: Get the Openvswitch stable release
  get_url: url=http://openvswitch.org/releases/openvswitch-1.10.0.tar.gz dest=/root/rpmbuild/SOURCES/
  when: vswitch_version.stdout != '1.10.0'
  tags: install       

- name: Copy the kmod spec file
  copy: src=openvswitch-kmod.files dest=/root/rpmbuild/SOURCES/
  tags: install       

- name: Copy the spec files for rpmbuild
  copy: src={{ item }} dest=/root
  with_items:
    - openvswitch-kmod-rhel6.spec
    - openvswitch.spec
  tags: install       

- name: Build the Openvswitch kernel module.
  shell: chdir=/root rpmbuild -bb /root/openvswitch-kmod-rhel6.spec
         creates=/root/rpmbuild/RPMS/x86_64/kmod-openvswitch-1.10.0-1.el6.x86_64.rpm 
  tags: install       

- name: Build the Openvswitch userspace application.
  shell: chdir=/root rpmbuild -bb /root/openvswitch.spec
         creates=/root/rpmbuild/RPMS/x86_64/openvswitch-1.10.0-1.x86_64.rpm 
  tags: install       

- name: Install the custom vswitch  kernel rpm.
  shell: yum -y localinstall /root/rpmbuild/RPMS/x86_64/kmod-openvswitch-1.10.0-1.el6.x86_64.rpm
         creates=/lib/modules/2.6.32-358.2.1.el6.x86_64/extra/openvswitch/openvswitch.ko
  tags: install       

- name: Check the custom vswitch kernel rpm
  rpm:  names=kmod-openvswitch state=present
  tags: check

- name: Install the custom openvswitch rpm
  shell: yum -y localinstall /root/rpmbuild/RPMS/x86_64/openvswitch-1.10.0-1.x86_64.rpm
         creates=/usr/share/doc/openvswitch-1.10.90/FAQ
  tags: install       

- name: Check the custom vswitch kernel rpm
  rpm:  names=openvswitch state=present
  tags: check


- name: Create the hosts entry.
  template: src=hosts.j2 dest=/etc/hosts
  tags: setup       

- name: start the openvswitch service.
  service: name=openvswitch state=started
  tags: setup       

- name: Disable selinux dynamically
  shell: creates=/etc/sysconfig/selinux.disabled setenforce 0 ; touch /etc/sysconfig/selinux.disabled
  tags: setup       

- name: Disable SELinux in conf file
  copy: src=selinux dest=/etc/sysconfig/selinux
  tags: setup       

- name: Disable iptables
  service: name=iptables state=stopped enabled=no
  tags: setup       



